import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def fetch_nifty_data(nifty_symbols):
    # Define Nifty 50 symbols (you can extend this list with more symbols)
   
    # Set the period for historical data
    end_date = datetime.now()
    start_date = end_date - timedelta(days=365)  # 1 year of data
   
    # Fetch historical data for all symbols
    data = {}
    for symbol in nifty_symbols:
        data[symbol] = yf.download(symbol, start=start_date, end=end_date)
   
    return data

def calculate_momentum(data):
    # Calculate 6-month returns as a measure of momentum
    momentum_scores = {}
    for symbol, df in data.items():
        try:
            df['6M_Return'] = df['Adj Close'].pct_change(periods=126)  # Approx. 6 months (252 trading days in a year)
            momentum_scores[symbol] = df['6M_Return'].iloc[-1]
        except:
            momentum_scores[symbol] = np.nan  # Handle cases where data is insufficient
   
    # Rank stocks by their 6-month returns
    momentum_stocks = sorted(momentum_scores.items(), key=lambda x: x[1], reverse=True)
    return momentum_stocks

def find_value_stocks(data):
    # Fetch current P/E ratios for value investing
    pe_ratios = {}
    for symbol in data.keys():
        ticker = yf.Ticker(symbol)
        try:
            pe_ratios[symbol] = ticker.info['trailingPE']
        except KeyError:
            pe_ratios[symbol] = np.nan  # Handle missing data
   
    # Rank stocks by their P/E ratio (lower P/E suggests better value)
    value_stocks = sorted(pe_ratios.items(), key=lambda x: x[1])
    return value_stocks

'''
Below section run teh scripts
'''
midcap=['EIDPARRY',
'TRIVENI',
'RCF',
'ALOKINDS',
'CHAMBLFERT',
'RENUKA',
'SUNTECK',
'JUBLINGREA',
'RKFORGE',
'HEG',
'HSCL',
'360ONE',
'DEEPAKFERT',
'TEJASNET',
'GSFC',
'PRSMJOHNSN',
'CRAFTSMAN',
'MOTILALOFS',
'RBLBANK',
'GRAPHITE',
'TRITURBINE',
'SCHNEIDER',
'RTNINDIA',
'HFCL',
'LXCHEM',
'EQUITASBNK',
'BALRAMCHIN',
'KIMS',
'NUVAMA',
'SAPPHIRE',
'GPIL',
'INDIAMART',
'ARE&M',
'NBCC',
'MASTEK',
'ACE',
'CLEAN',
'BLS',
'DCMSHRIRAM',
'CASTROLIND',
'FIVESTAR',
'ACI',
'AAVAS',
'HUDCO',
'MAPMYINDIA',
'APTUS',
'ZENSARTECH',
'WESTLIFE',
'AVANTIFEED',
'CSBBANK',
'NAVINFLUOR',
'FINEORG',
'UCOBANK',
'BSOFT',
'JINDALSAW',
'SYRMA',
'PCBL',
'IDFC',
'ALKYLAMINE',
'J&KBANK',
'CENTRALBK',
'JBCHEPHARM',
'SONATSOFTW',
'HAPPSTMNDS',
'AFFLE',
'INTELLECT',
'SAREGAMA',
'TMB',
'ECLERX',
'HBLPOWER',
'KARURVYSYA',
'RAJESHEXPO',
'ELGIEQUIP',
'IOB',
'FDC',
'CENTURYPLY',
'CUB',
'GODFRYPHLP',
'GNFC',
'BALAMINES',
'SANOFI',
'LEMONTREE',
'CERA',
'HAPPYFORGE',
'NETWORK18',
'ERIS',
'ASAHIINDIA',
'GLENMARK',
'ELECON',
'MMTC',
'TITAGARH',
'FSL',
'CELLO',
'AMBER',
'CHOLAHLDNG',
'CAPLIPOINT',
'GSPL',
'MRPL',
'SWANENERGY',
'RRKABEL',
'MHRIL',
'SHYAMMETL',
'RBA',
'NAM-INDIA',
'MANAPPURAM',
'VIPIND',
'SBFC',
'MAHLIFE',
'RADICO',
'FINCABLES',
'SAFARI',
'WHIRLPOOL',
'LATENTVIEW',
'POLYMED',
'TVSSCS',
'TV18BRDCST',
'INDIACEM',
'POWERINDIA',
'STLTECH',
'JUBLPHARMA',
'INDIGOPNTS',
'ANANDRATHI',
'AARTIIND',
'CROMPTON',
'GAEL',
'PVRINOX',
'KAYNES',
'HOMEFIRST',
'OLECTRA',
'ASTERDM',
'EIHOTEL',
'EXIDEIND',
'JUSTDIAL',
'ITI',
'APLLTD',
'GRANULES',
'CAMPUS',
'NLCINDIA',
'TRIDENT',
'VGUARD',
'EPL',
'UJJIVANSFB',
'ROUTE',
'FINPIPE',
'IBULHSGFIN',
'MCX',
'PRINCEPIPE',
'PRAJIND',
'SWSOLAR',
'EASEMYTRIP',
'GMDCLTD',
'JKLAKSHMI',
'TTML',
'CESC',
'KPIL',
'APARINDS',
'VIJAYA',
'METROPOLIS',
'CDSL',
'DOMS',
'AETHER',
'CHENNPETRO',
'ASTRAZEN',
'CONCORDBIO',
'JYOTHYLAB',
'RATNAMANI',
'MEDPLUS',
'BIRLACORPN',
'BORORENEW',
'KRBL',
'JBMA',
'GPPL',
'CYIENT',
'NATIONALUM',
'NH',
'BBTC',
'REDINGTON',
'BLUESTARCO',
'CIEINDIA',
'HINDCOPPER',
'ANURAS',
'CGCL',
'SPARC',
'MEDANTA',
'CAMS',
'TANLA',
'NUVOCO',
'CEATLTD',
'SUVENPHAR',
'PPLPHARMA',
'ANGELONE',
'VAIBHAVGBL',
'JWL',
'UTIAMC',
'GLS',
'IIFL',
'CREDITACC',
'CCL',
'BIKAJI',
'BLUEDART',
'KSB',
'MGL',
'NSLNISP',
'VARROC',
'WELCORP',
'HONASA',
'CHALET',
'IRCON',
'MTARTECH',
'MINDACORP',
'JMFINANCIL',
'RAYMOND',
'CHEMPLASTS',
'CANFINHOME',
'RITES',
'MAHSEAMLES',
'JAIBALAJI',
'VTL',
'NCC',
'DATAPATTNS',
'USHAMART',
'RAILTEL',
'PNBHOUSING',
'RAINBOW',
'ENGINERSIN',
'PNCINFRA',
'GMMPFAUDLR',
'IEX',
'ALLCARGO',
'WELSPUNLIV',
'TATAINVEST',
'COCHINSHIP',
'NATCOPHARM',
'CENTURYTEX',
'INOXWIND',
'GRSE',
'KFINTECH',
'QUESS',
'IRB',
'GESHIP',
'KNRCON',
'BEML',
'GILLETTE',
'RHIM',
'JKPAPER',
'SOBHA',
'BRIGADE',
'SIGNATURE',
'KEC',
'AEGISLOG'
   ]

symbols=[symbol + '.NS' for symbol in midcap]
data=fetch_nifty_data(symbols)
momentum_stocks=calculate_momentum(data)
value_stocks=find_value_stocks(data)
print(value_stocks[:10])